- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:TraitsRequirement # No Pacifist or Blind Sec
    inverted: true
    traits:
    - Pacifist
    - Blindness
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Detective
  - Cryogenics
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
    shoes: ClothingShoesBootsJackFilled # GreyStation Addition
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
    pocket2: ClothingNeckDetectiveBadge # GreyStation Addition
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
