- type: job
  id: PrisonGuard
  name: job-name-guard
  description: job-description-guard
  setPreference: false # GreyStation - Only the prison map will have prison guards.
  playTimeTracker: JobPrisonGuard
  startingGear: PrisonGuardGear
  canBeAntag: false
  icon: "JobIconPrisonGuard"
  supervisors: job-supervisors-warden
  access:
  - Security
  - Brig
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]


- type: startingGear
  id: PrisonGuardGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisonGuard
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadPrisonGuard
    id: PrisonGuardPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  storage:
    back:
    - BoxSurvivalSecurity
    - Flash