# Configuration preset used on Wizard's Den Leviathan

[game]
desc = "Official English Space Station 14 servers. Vanilla, roleplay ruleset. "
hostname = "[EN][Dev Branch] Wizard's Den Vulture [US East 2]"

[hub]
tags = "lang:en,region:am_n_e,rp:low"

[server]
lobby_name = "TEST SERVER Vulture"

[chat]
motd = "\n##############:3########################################\n\nThis server is running the development branch. You can see upcoming changes ahead of the next bi-weekly release, but they may not be final.\nRead the Changelog for more information.\n\nFeatures and changes on this server may be rolled back before release.\nPlease report any bugs you find, via github or Discord. Thank you!\n\n#######################################################"
