- type: gameMapPool
  id: DefaultMapPool
  maps:
  #- Aspid
  #- Atlas
  - Bagel
  - Box
  #- Cluster
  #- Core
  #- Cog
  #- Fland
  #- Gemini
  - Marathon
  - Meta
  #- Omega
  #- Oasis
  #- Origin
  #- Saltern
  #- Packed
  #- Reach
  #- Train
