- type: gameMapPool
  id: DefaultMapPool
  maps:
  #- Aspid
  #- Atlas
  - Bagel
  - Box
  #- Cluster
  #- Core
  - Fland
  #- Gemini
  - Marathon
  - Meta
  #- Omega
  - Oasis
  - Origin
  #- Saltern
  #- Packed
  - Reach
  - Train
