- type: job
  id: MartialArtist
  name: job-name-martialartist
  description: job-description-martialartist
  playTimeTracker: JobMartialArtist
  setPreference: false
  startingGear: MartialArtistGear
  icon: "JobIconMartialArtist"
  supervisors: job-supervisors-hop
  access:
  - Service
  extendedAccess:
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: Boxer
      modifiers:
        coefficients: # These only apply to unarmed
          Blunt: 1.5
          Slash: 1.5
          Piercing: 1.5

- type: startingGear
  id: MartialArtistGear
  equipment:
    jumpsuit: ClothingUniformMartialGi
    belt: ClothingBeltMartialBlack
    id: MartialArtistPDA
    ears: ClothingHeadsetService
    shoes: ClothingShoesGeta
    gloves: ClothingHandsGlovesBoxingRed
  storage:
    back:
    - BoxSurvival