# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  setPreference: false
  startingGear: ERTLeaderGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTLeader
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbing
    neck: Whistle
    pocket1: WeaponPistolN1984
    pocket2: FlashlightSeclite
  storage:
    back:
    - BoxZiptie
    - MedkitCombatFilled
    - CrowbarRed
    - GrenadeFlashBang
    - GrenadeStinger
    - WeaponDisabler
    belt:
    - Stunbaton
    - HoloprojectorSecurity
    - MagazineMagnum

- type: startingGear
  id: ERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbing
    neck: Whistle
    pocket1: WeaponPistolN1984
  storage:
    back:
    - BoxZiptie
    - MedkitCombatFilled
    - CrowbarRed
    - GrenadeFlashBang
    - GrenadeStinger
    - WeaponDisabler
    belt:
    - Stunbaton
    - HoloprojectorSecurity
    - MagazineMagnum
    - CombatKnife

- type: startingGear
  id: ERTMarinesGearLeader
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbing
    neck: Whistle
    pocket1: WeaponPistolN1984
    pocket2: WeaponDisabler
  storage:
    back:
    - BoxZiptie
    - WeaponSubMachineGunDrozd
    - MedkitCombatFilled
    - CrowbarRed
    - CombatKnife
    - GrenadeFlashBang
    - GrenadeStinger
    belt:
    - Stunbaton
    - HoloprojectorSecurity
    - MagazineMagnum
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun

# Chaplain
- type: job
  id: ERTChaplain
  name: job-name-ertchaplain
  description: job-description-ertchaplain
  playTimeTracker: JobERTChaplain
  setPreference: false
  startingGear: ERTChaplainGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles

- type: startingGear
  id: ERTChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltStorageWaistbag
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - BoxBodyBag
    - BoxCandle
    - MagazinePistol
    - CrowbarRed
    - Bible
    - Lighter
    - DrinkWaterMelonJuiceJug
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    belt:
    - Lantern
    - Lantern
    - Lantern
    - Lantern

- type: startingGear
  id: ERTChaplainGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltStorageWaistbag
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - BoxBodyBag
    - BoxCandle
    - MagazinePistol
    - CrowbarRed
    - Bible
    - Lighter
    - DrinkWaterMelonJuiceJug
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    belt:
    - Lantern
    - Lantern
    - Lantern
    - Lantern

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTEngineer
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltUtility
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - RCD
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - SheetSteel
    - CableApcStack
    - CableMVStack
    - MagazinePistol
    - SheetGlass
    - SheetPlasteel
    - SheetSteel
    - CableHVStack
    - CombatKnife
    belt:
    - JawsOfLife
    - PowerDrill
    - WelderExperimental
    - Multitool
    - HolofanProjector
    - GasAnalyzer
    - trayScanner

- type: startingGear
  id: ERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltUtility
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - RCD
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - SheetSteel
    - CableApcStack
    - CableMVStack
    - MagazinePistol
    - SheetGlass
    - SheetPlasteel
    - SheetSteel
    - CableHVStack
    belt:
    - JawsOfLife
    - PowerDrill
    - WelderExperimental
    - Multitool
    - HolofanProjector
    - GasAnalyzer
    - trayScanner

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbing
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - BoxZiptie
    - MedkitCombatFilled
    - TelescopicShield
    - CrowbarRed
    - WeaponDisablerSMG
    belt:
    - Stunbaton
    - HoloprojectorSecurity
    - MagazinePistol
    - GrenadeFlashBang
    - GrenadeStinger

- type: startingGear
  id: ERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbing
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - BoxZiptie
    - MedkitCombatFilled
    - TelescopicShield
    - CrowbarRed
    - WeaponDisablerSMG
    - CombatKnife
    belt:
    - Stunbaton
    - HoloprojectorSecurity
    - MagazinePistol
    - GrenadeFlashBang
    - GrenadeStinger

- type: startingGear
  id: ERTMarinesGearRifleman
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbing
    pocket1: WeaponPistolMk58
    pocket2: WeaponDisabler
  storage:
    back:
    - BoxZiptie
    - WeaponRifleLecter
    - GrenadeFlashBang
    - CombatKnife
    - MedkitCombatFilled
    - CrowbarRed
    - TelescopicShield
    belt:
    - Stunbaton
    - HoloprojectorSecurity
    - MagazinePistol
    - MagazineRifle
    - MagazineRifle
    - MagazineRifle
    - MagazineRifle

- type: startingGear
  id: ERTMarinesGearBreacher
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbing
    pocket1: WeaponPistolMk58
    pocket2: WeaponDisabler
  storage:
    back:
    - BoxZiptie
    - WeaponShotgunEnforcer
    - GrenadeFlashBang
    - MedkitCombatFilled
    - JawsOfLife
    - C4NT
    - C4NT
    - C4NT
    - C4NT
    - C4NT
    - CombatKnife
    belt:
    - Stunbaton
    - HoloprojectorSecurity
    - MagazinePistol
    - BoxLethalshot
    - BoxLethalshot


- type: startingGear
  id: ERTMarinesGearGrenadier
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbing
    pocket1: WeaponPistolMk58
    pocket2: WeaponDisabler
  storage:
    back:
    - BoxZiptie
    - WeaponSubMachineGunDrozd
    - MedkitCombatFilled
    - CrowbarRed
    - GrenadeFlashBang
    - GrenadeFlashBang
    - SmokeGrenade
    - SmokeGrenade
    - SmokeGrenade
    - GrenadeShrapnelNT
    - GrenadeShrapnelNT
    - GrenadeShrapnelNT
    - CombatKnife
    belt:
    - Stunbaton
    - HoloprojectorSecurity
    - MagazinePistol
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun



# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  setPreference: false
  startingGear: ERTMedicalGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTMedicalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTMedic
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMedicalEMT
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - BoxBodyBag
    - Defibrillator
    - MedkitCombatFilled
    - MagazinePistol
    - CrowbarRed
    - Hypospray
    - OmnizineChemistryBottle
    - EpinephrineChemistryBottle
    - EpinephrineChemistryBottle
    belt:
    - AntiPoisonMedipen
    - AntiPoisonMedipen
    - BruteAutoInjector
    - BruteAutoInjector
    - BruteAutoInjector
    - AirlossAutoInjector
    - AirlossAutoInjector
    - AirlossAutoInjector
    - RadAutoInjector
    - RadAutoInjector
    - PunctAutoInjector
    - PunctAutoInjector
    - PunctAutoInjector
    - PyraAutoInjector
    - PyraAutoInjector
    - PyraAutoInjector

- type: startingGear
  id: ERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMedicalEMT
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - BoxBodyBag
    - Defibrillator
    - MedkitCombatFilled
    - MagazinePistol
    - CrowbarRed
    - MagazinePistol
    - Hypospray
    - OmnizineChemistryBottle
    - EpinephrineChemistryBottle
    - EpinephrineChemistryBottle
    belt:
    - AntiPoisonMedipen
    - AntiPoisonMedipen
    - BruteAutoInjector
    - BruteAutoInjector
    - BruteAutoInjector
    - AirlossAutoInjector
    - AirlossAutoInjector
    - AirlossAutoInjector
    - RadAutoInjector
    - RadAutoInjector
    - PunctAutoInjector
    - PunctAutoInjector
    - PunctAutoInjector
    - PyraAutoInjector
    - PyraAutoInjector
    - PyraAutoInjector

- type: startingGear
  id: ERTMarinesGearMedic
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedSec
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMedicalEMT
    pocket1: WeaponPistolMk58
    pocket2: WeaponDisabler
  storage:
    back:
    - BoxBodyBag
    - WeaponSubMachineGunDrozd
    - MedkitCombatFilled
    - Defibrillator
    - CrowbarRed
    - Hypospray
    - MagazinePistol
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - PunctAutoInjector
    - PunctAutoInjector
    - OmnizineChemistryBottle
    - EpinephrineChemistryBottle
    - Gauze
    belt:
    - AntiPoisonMedipen
    - AntiPoisonMedipen
    - BruteAutoInjector
    - BruteAutoInjector
    - BruteAutoInjector
    - AirlossAutoInjector
    - AirlossAutoInjector
    - AirlossAutoInjector
    - RadAutoInjector
    - RadAutoInjector
    - PunctAutoInjector
    - PunctAutoInjector
    - PunctAutoInjector
    - PyraAutoInjector
    - PyraAutoInjector
    - PyraAutoInjector

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTJanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesGaloshes
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTJanitor
    eyes: ClothingEyesGlassesChemical
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitor
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - BoxLightMixed
    - BoxLightMixed
    - MagazinePistol
    - CrowbarRed
    - AdvMopItem
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CombatKnife
    belt:
    - SoapNT
    - MegaSprayBottleSpaceCleaner
    - LightReplacer
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - TrashBag

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesChemical
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterHardsuitERTJanitor
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitor
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - BoxLightMixed
    - BoxLightMixed
    - MagazinePistol
    - CrowbarRed
    - AdvMopItem
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CombatKnife
    belt:
    - SoapNT
    - MegaSprayBottleSpaceCleaner
    - LightReplacer
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - TrashBag