- type: entity
  id: CrateServiceKendo
  parent: CrateGenericSteel
  name: kendo kit crate
  description: Contains multiple gi, hakama, shinais, and kendo armor.
  components:
  - type: StorageFill
    contents:
    - id: ClothingHeadHelmetKendoMen
      amount: 2
    - id: ClothingOuterArmorKendoBogu
      amount: 2
    - id: Shinai
      amount: 2