# TODO: Actual wizard coming later, this is just for the survival antags

- type: antag
  id: Survivor
  name: roles-antag-survivor-name
  antagonist: true
  objective: roles-antag-survivor-objective
  requirements: # I hate time locked roles but this should be enough time for someone to be acclimated
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  # guides: [  ]

- type: antag
  id: Wizard
  name: roles-antag-wizard-name
  antagonist: true
  setPreference: true
  objective: roles-antag-wizard-objective # TODO: maybe give random objs and stationary ones from AntagObjectives and AntagRandomObjectives
  # TODO: WizardGuide
  # guides: [  ]

# See wizard_startinggear for wiz start gear options
